logging.level:
  root: INFO
  com.dstools.wstools: DEBUG
  org:
    springframework:
      web:
        socket: DEBUG


socket.uri: '/socket'
socket.uri.applicationDestination: '/topic'
socket.uri.brokerDestination: '/publish'
socket.uri.sendToBroker.enabled: true
